services:
  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management-alpine"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      #- VIRTUAL_HOST=/
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
